FROM node:lts-alpine

WORKDIR /app

COPY build/bugsnag-source-maps.tgz build/bugsnag-source-maps.tgz
COPY src/ src/
COPY package.json .
COPY package-lock.json .
COPY babel.config.browser.json .
COPY babel.config.node.json .

RUN npm ci
RUN npm install -g ./build/bugsnag-source-maps.tgz
RUN npm run build-single -- --config-file $(pwd)/babel.config.browser.json
